import { ROLE } from '@/constants'
import type { RoleId } from '@/constants'
import type { PortalId } from '@/constants'
import { PORTAL } from '@/constants'

export const PERMISSION = {
  ORGANIZATION_READ: 'organization.read',
  ORGANIZATION_EDIT: 'organization.edit',
  ORGANIZATION_MANAGE: 'organization.manage',
  ASSETS_READ: 'assets.read',
  ASSETS_CREATE: 'assets.create',
  ASSETS_EDIT: 'assets.edit',
  FINANCE_READ: 'finance.read',
  FINANCE_EDIT: 'finance.edit',
  /** Provisional: SOE contributor edits industrial data */
  INDUSTRIAL_EDIT: 'industrial.edit',
  ACCOUNTABILITY_READ: 'accountability.read',
  PROCUREMENT_EDIT: 'procurement.edit',
  AUDIT_EDIT: 'audit.edit',
  LITIGATION_EDIT: 'litigation.edit',
  COMPLIANCE_EDIT: 'compliance.edit',
  PRIVATIZATION_EDIT: 'privatization.edit',
  WORKFORCE_READ: 'workforce.read',
  WORKFORCE_EDIT: 'workforce.edit',
  BOARD_READ: 'board.read',
  BOARD_EDIT: 'board.edit',
  SENSITIVE_PERSONAL_READ: 'sensitive.personal.read',
  SENSITIVE_REMUNERATION_READ: 'sensitive.remuneration.read',
  SUBMISSION_SUBMIT: 'submission.submit',
  SUBMISSION_CERTIFY: 'submission.certify',
  SUBMISSION_REVIEW: 'submission.review',
  SUBMISSION_APPROVE: 'submission.approve',
  CLARIFICATION_CREATE: 'clarification.create',
  DOCUMENT_UPLOAD: 'document.upload',
  DOCUMENT_READ: 'document.read',
  DOCUMENT_VERIFY: 'document.verify',
  /** Provisional: create MoIP escalations / tasks */
  ESCALATION_CREATE: 'escalation.create',
  EXECUTIVE_DASHBOARD_READ: 'executive.dashboard.read',
  PORTFOLIO_READ: 'portfolio.read',
  USER_READ: 'user.read',
  USER_MANAGE: 'user.manage',
  AUDIT_LOG_READ: 'audit_log.read',
} as const

export type Permission = (typeof PERMISSION)[keyof typeof PERMISSION]

const soeOpsBase: Permission[] = [
  PERMISSION.ORGANIZATION_READ,
  PERMISSION.ASSETS_READ,
  PERMISSION.FINANCE_READ,
  PERMISSION.WORKFORCE_READ,
  PERMISSION.BOARD_READ,
  PERMISSION.ACCOUNTABILITY_READ,
  PERMISSION.DOCUMENT_READ,
  PERMISSION.DOCUMENT_UPLOAD,
]

const rolePermissions: Record<RoleId, Permission[]> = {
  [ROLE.SOE_FOCAL_PERSON]: [
    ...soeOpsBase,
    PERMISSION.ORGANIZATION_EDIT,
    PERMISSION.ASSETS_CREATE,
    PERMISSION.ASSETS_EDIT,
    PERMISSION.FINANCE_EDIT,
    PERMISSION.INDUSTRIAL_EDIT,
    PERMISSION.WORKFORCE_EDIT,
    PERMISSION.BOARD_EDIT,
    PERMISSION.PROCUREMENT_EDIT,
    PERMISSION.AUDIT_EDIT,
    PERMISSION.LITIGATION_EDIT,
    PERMISSION.COMPLIANCE_EDIT,
    PERMISSION.PRIVATIZATION_EDIT,
    PERMISSION.SUBMISSION_SUBMIT,
    PERMISSION.SENSITIVE_PERSONAL_READ,
    PERMISSION.SENSITIVE_REMUNERATION_READ,
  ],
  [ROLE.SOE_DATA_CONTRIBUTOR]: [
    ...soeOpsBase,
    PERMISSION.ORGANIZATION_EDIT,
    PERMISSION.ASSETS_CREATE,
    PERMISSION.ASSETS_EDIT,
    PERMISSION.FINANCE_EDIT,
    PERMISSION.INDUSTRIAL_EDIT,
    PERMISSION.WORKFORCE_EDIT,
    PERMISSION.BOARD_EDIT,
    PERMISSION.PROCUREMENT_EDIT,
    PERMISSION.AUDIT_EDIT,
    PERMISSION.LITIGATION_EDIT,
    PERMISSION.COMPLIANCE_EDIT,
    PERMISSION.PRIVATIZATION_EDIT,
    PERMISSION.SENSITIVE_PERSONAL_READ,
    PERMISSION.SENSITIVE_REMUNERATION_READ,
  ],
  [ROLE.SOE_CERTIFIER]: [
    PERMISSION.ORGANIZATION_READ,
    PERMISSION.ACCOUNTABILITY_READ,
    PERMISSION.COMPLIANCE_EDIT,
    PERMISSION.DOCUMENT_READ,
    PERMISSION.DOCUMENT_UPLOAD,
    PERMISSION.SUBMISSION_CERTIFY,
  ],
  [ROLE.SOE_EXECUTIVE]: [
    PERMISSION.EXECUTIVE_DASHBOARD_READ,
    PERMISSION.ORGANIZATION_READ,
    PERMISSION.ASSETS_READ,
    PERMISSION.FINANCE_READ,
    PERMISSION.WORKFORCE_READ,
    PERMISSION.BOARD_READ,
    PERMISSION.ACCOUNTABILITY_READ,
    PERMISSION.DOCUMENT_READ,
  ],
  [ROLE.FINANCE_OFFICER]: [
    ...soeOpsBase,
    PERMISSION.FINANCE_EDIT,
    PERMISSION.DOCUMENT_UPLOAD,
  ],
  [ROLE.HR_OFFICER]: [
    ...soeOpsBase,
    PERMISSION.WORKFORCE_EDIT,
    PERMISSION.SENSITIVE_PERSONAL_READ,
    PERMISSION.SENSITIVE_REMUNERATION_READ,
  ],
  [ROLE.ASSET_OFFICER]: [
    ...soeOpsBase,
    PERMISSION.ASSETS_CREATE,
    PERMISSION.ASSETS_EDIT,
  ],
  [ROLE.COMPANY_SECRETARY]: [
    ...soeOpsBase,
    PERMISSION.ORGANIZATION_EDIT,
    PERMISSION.BOARD_EDIT,
    PERMISSION.COMPLIANCE_EDIT,
    PERMISSION.PRIVATIZATION_EDIT,
    PERMISSION.SENSITIVE_PERSONAL_READ,
    PERMISSION.SENSITIVE_REMUNERATION_READ,
  ],
  [ROLE.LEGAL_OFFICER]: [...soeOpsBase, PERMISSION.LITIGATION_EDIT],
  [ROLE.PROCUREMENT_OFFICER]: [...soeOpsBase, PERMISSION.PROCUREMENT_EDIT],
  [ROLE.INTERNAL_AUDIT]: [...soeOpsBase, PERMISSION.AUDIT_EDIT],
  [ROLE.CEO]: [
    ...soeOpsBase,
    PERMISSION.SUBMISSION_CERTIFY,
    PERMISSION.SUBMISSION_SUBMIT,
    PERMISSION.SENSITIVE_REMUNERATION_READ,
  ],
  [ROLE.CFO]: [
    ...soeOpsBase,
    PERMISSION.FINANCE_EDIT,
    PERMISSION.AUDIT_EDIT,
    PERMISSION.SUBMISSION_CERTIFY,
  ],
  [ROLE.MOIP_REVIEWER]: [
    PERMISSION.ORGANIZATION_READ,
    PERMISSION.ORGANIZATION_MANAGE,
    PERMISSION.ASSETS_READ,
    PERMISSION.FINANCE_READ,
    PERMISSION.WORKFORCE_READ,
    PERMISSION.BOARD_READ,
    PERMISSION.ACCOUNTABILITY_READ,
    PERMISSION.DOCUMENT_READ,
    PERMISSION.DOCUMENT_VERIFY,
    PERMISSION.PORTFOLIO_READ,
    PERMISSION.SUBMISSION_REVIEW,
    PERMISSION.CLARIFICATION_CREATE,
    PERMISSION.SUBMISSION_APPROVE,
    PERMISSION.ESCALATION_CREATE,
    PERMISSION.USER_READ,
    PERMISSION.USER_MANAGE,
    PERMISSION.AUDIT_LOG_READ,
  ],
  [ROLE.MOIP_ANALYST]: [
    PERMISSION.ORGANIZATION_READ,
    PERMISSION.ASSETS_READ,
    PERMISSION.FINANCE_READ,
    PERMISSION.WORKFORCE_READ,
    PERMISSION.BOARD_READ,
    PERMISSION.ACCOUNTABILITY_READ,
    PERMISSION.DOCUMENT_READ,
    PERMISSION.PORTFOLIO_READ,
  ],
  [ROLE.MOIP_SUPERVISOR]: [
    PERMISSION.ORGANIZATION_READ,
    PERMISSION.ASSETS_READ,
    PERMISSION.FINANCE_READ,
    PERMISSION.PORTFOLIO_READ,
    PERMISSION.WORKFORCE_READ,
    PERMISSION.BOARD_READ,
    PERMISSION.ACCOUNTABILITY_READ,
    PERMISSION.DOCUMENT_READ,
    PERMISSION.DOCUMENT_VERIFY,
    PERMISSION.SUBMISSION_REVIEW,
    PERMISSION.SUBMISSION_APPROVE,
    PERMISSION.CLARIFICATION_CREATE,
    PERMISSION.ESCALATION_CREATE,
    PERMISSION.ORGANIZATION_MANAGE,
    PERMISSION.AUDIT_LOG_READ,
  ],
  [ROLE.EXECUTIVE_VIEWER]: [
    PERMISSION.PORTFOLIO_READ,
    PERMISSION.EXECUTIVE_DASHBOARD_READ,
    PERMISSION.ORGANIZATION_READ,
    PERMISSION.FINANCE_READ,
    PERMISSION.ASSETS_READ,
    PERMISSION.BOARD_READ,
    PERMISSION.WORKFORCE_READ,
    PERMISSION.ACCOUNTABILITY_READ,
    PERMISSION.DOCUMENT_READ,
  ],
  [ROLE.SECRETARY]: [
    PERMISSION.PORTFOLIO_READ,
    PERMISSION.EXECUTIVE_DASHBOARD_READ,
    PERMISSION.ORGANIZATION_READ,
    PERMISSION.FINANCE_READ,
    PERMISSION.BOARD_READ,
    PERMISSION.WORKFORCE_READ,
    PERMISSION.ACCOUNTABILITY_READ,
    PERMISSION.DOCUMENT_READ,
  ],
  [ROLE.MINISTER]: [
    PERMISSION.PORTFOLIO_READ,
    PERMISSION.EXECUTIVE_DASHBOARD_READ,
    PERMISSION.ORGANIZATION_READ,
    PERMISSION.FINANCE_READ,
    PERMISSION.ASSETS_READ,
    PERMISSION.BOARD_READ,
    PERMISSION.WORKFORCE_READ,
    PERMISSION.ACCOUNTABILITY_READ,
    PERMISSION.DOCUMENT_READ,
  ],
  [ROLE.PMO]: [
    PERMISSION.PORTFOLIO_READ,
    PERMISSION.EXECUTIVE_DASHBOARD_READ,
    PERMISSION.ORGANIZATION_READ,
    PERMISSION.FINANCE_READ,
    PERMISSION.ASSETS_READ,
    PERMISSION.BOARD_READ,
    PERMISSION.ACCOUNTABILITY_READ,
    PERMISSION.DOCUMENT_READ,
  ],
  [ROLE.ASSURANCE_USER]: [
    PERMISSION.ORGANIZATION_READ,
    PERMISSION.FINANCE_READ,
    PERMISSION.ASSETS_READ,
    PERMISSION.BOARD_READ,
    PERMISSION.ACCOUNTABILITY_READ,
    PERMISSION.DOCUMENT_READ,
  ],
  [ROLE.SYSTEM_ADMIN]: Object.values(PERMISSION),
}

export function getPermissionsForRole(role: RoleId): Permission[] {
  return rolePermissions[role] ?? []
}

export function hasPermission(role: RoleId, permission: Permission): boolean {
  return getPermissionsForRole(role).includes(permission)
}

export function getPortalForRole(role: RoleId): PortalId {
  if (
    role === ROLE.MOIP_REVIEWER ||
    role === ROLE.MOIP_ANALYST ||
    role === ROLE.MOIP_SUPERVISOR ||
    role === ROLE.SYSTEM_ADMIN
  ) {
    return PORTAL.MOIP
  }
  if (role === ROLE.EXECUTIVE_VIEWER) return PORTAL.MINISTER
  if (role === ROLE.SECRETARY) return PORTAL.SECRETARY
  if (role === ROLE.MINISTER) return PORTAL.MINISTER
  if (role === ROLE.PMO) return PORTAL.PMO
  if (role === ROLE.ASSURANCE_USER) return PORTAL.ASSURANCE
  return PORTAL.SOE
}

export function getHomeForRole(role: RoleId): string {
  if (role === ROLE.SYSTEM_ADMIN) return '/moip/admin/users'
  if (role === ROLE.SOE_EXECUTIVE) return '/soe/executive'
  if (
    role === ROLE.MOIP_REVIEWER ||
    role === ROLE.MOIP_ANALYST ||
    role === ROLE.MOIP_SUPERVISOR
  ) {
    return '/moip/dashboard'
  }
  if (role === ROLE.EXECUTIVE_VIEWER || role === ROLE.MINISTER) return '/minister/dashboard'
  if (role === ROLE.SECRETARY) return '/secretary/dashboard'
  if (role === ROLE.PMO) return '/pmo/dashboard'
  if (role === ROLE.ASSURANCE_USER) return '/assurance/dashboard'
  return '/soe/dashboard'
}

export const DEMO_ROLES: RoleId[] = [
  ROLE.SOE_FOCAL_PERSON,
  ROLE.SOE_CERTIFIER,
  ROLE.SOE_EXECUTIVE,
  ROLE.MOIP_REVIEWER,
  ROLE.MOIP_SUPERVISOR,
  ROLE.EXECUTIVE_VIEWER,
]
